apply from: "https://raw.githubusercontent.com/BIVA-MX/biva-build-config/maint/java21/java/general/general.gradle"
apply from: "https://raw.githubusercontent.com/BIVA-MX/biva-build-config/maint/java21/java/jacoco/jacoco.gradle"
apply from: "https://raw.githubusercontent.com/BIVA-MX/biva-build-config/maint/java21/java/repository/read-repo.gradle"
apply from: "https://raw.githubusercontent.com/BIVA-MX/biva-build-config/maint/java21/java/checkstyle/checkstyle.gradle"
